### ISSUE TITLE
Make parens optional for single argument

### ISSUE THREAD

**Issue by alfonsogarciacaro** [ikigai-go/compiler#7]
In #5 we've decided to use parens for functions with multiple arguments. However, and even if I want to avoid multiple alternatives for the same thing (especially at the beginning), given that the syntax will be ML-like, it may help to make the parens optional when there's only a single argument.

```
let add(x, y) = x + y // Two arguments, parens are enforced
let square x = x * x // One argument, parens are optional
let test() =
    square 4 // Also for application
```

Disadvantages:

- It could be a bit confusing to mix both styles (this already happens in F#). Although parens are also optional in arrow lambdas with only one argument `.map(x => x + 2)`.
- This creates ambiguity with indexers (e.g. `f[2]`) which would force us to use a dot as in F#: `ar.[2]` (Ocaml uses dot and parens `ar.(2)`, ReasonML uses parens always for application so they don't need the dot in indexing).

**Comment by alfonsogarciacaro** [comment]
If we don't have type inference or auto-generalization for arguments, most of the times you will need to add the parens in the declaration though:

```
let square (x: number) = x * x
```

**Comment by alfonsogarciacaro** [comment]
Upon reflection, maybe it's better not to do this a it can create a very inconsistent style: 0 arguments, empty parens; one argument, no parens; two or more arguments, parens...

**Comment by MangelMaxime** [comment]
I would prefer to make the parens mandatory so the syntax is consistent. When you have a function it will all be written using `let myFunc (....) = ....`
